---
- name: Build docker image and deploy to example hosting
  hosts: www
  roles:
    - role: practical-ansible.nginx_docker
      become: true
      vars:
        server_names: 'wiki.improliga.cz'
        project_name: cz-improliga-wiki
        project_version: '1.34.1-alpha-9'
        use_ssl: false
        env:
          DB_HOST: '{{ lookup("env", "DB_HOST") }}'
          DB_NAME: '{{ lookup("env", "DB_NAME") }}'
          DB_PASS: '{{ lookup("env", "DB_PASS") }}'
          DB_PORT: '{{ lookup("env", "DB_PORT") }}'
          DB_USER: '{{ lookup("env", "DB_USER") }}'
          MW_SECRET_KEY: '{{ lookup("env", "MW_SECRET_KEY") }}'
          MW_UPGRADE_KEY: '{{ lookup("env", "MW_UPGRADE_KEY") }}'
          S3_ACCESS_KEY_ID: '{{ lookup("env", "S3_ACCESS_KEY_ID") }}'
          S3_ACCESS_KEY_SECRET: '{{ lookup("env", "S3_ACCESS_KEY_SECRET") }}'
          S3_BUCKET_NAME: '{{ lookup("env", "S3_BUCKET_NAME") }}'
