---
name: Deployment
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 19
          docker_channel: stable
      - name: Install docker
        run: sudo apt-get -y install python-docker python3-docker
      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            deploy.yml
      - name: Install ansible deps
        run: ansible-galaxy install -r requirements.yml
      - name: Create inventory
        run: echo -e "[www]\n${{ secrets.DEPLOY_HOST }}\n" > inventory
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.DEPLOY_HOST_IDENT }}
      - name: Run deploy
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          MW_SECRET_KEY: ${{ secrets.MW_SECRET_KEY }}
          MW_UPGRADE_KEY: ${{ secrets.MW_UPGRADE_KEY }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_ACCESS_KEY_SECRET: ${{ secrets.S3_ACCESS_KEY_SECRET }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: ansible-playbook -i inventory deploy.yml
